import fs from "fs";
import path from "path";
import vm from "vm";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..");

function loadConfig() {
    const configPath = path.join(repoRoot, "assets", "js", "site.config.js");
    const code = fs.readFileSync(configPath, "utf8");
    const sandbox = { window: {} };
    vm.createContext(sandbox);
    vm.runInContext(code, sandbox);
    return sandbox.window.SiteConfig;
}

function walk(dir, files = []) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    entries.forEach((entry) => {
        if (entry.name.startsWith(".")) return;
        if (["node_modules", "vendor", ".git", "tools", "docs"].includes(entry.name)) {
            return;
        }
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            walk(fullPath, files);
        } else if (entry.isFile() && entry.name.endsWith(".html")) {
            files.push(fullPath);
        }
    });
    return files;
}

function toRoute(filePath) {
    const rel = path.relative(repoRoot, filePath).replace(/\\/g, "/");
    if (rel.endsWith("/index.html")) {
        const dir = rel.replace(/\/index\.html$/, "");
        return dir ? `/${dir}/` : "/";
    }
    return `/${rel}`;
}

function buildSitemap(routes, siteUrl) {
    const today = new Date().toISOString().split("T")[0];
    const lines = [
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
        "<!-- Generated by tools/generate-sitemap.mjs. Do not edit manually. -->",
        "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">",
    ];

    routes.forEach((route) => {
        const url = `${siteUrl.replace(/\/$/, "")}${route}`;
        const changefreq = route.includes("nobetci-eczaneler") ? "daily" : "monthly";
        const priority = route === "/" ? "1.0" : "0.7";
        lines.push("  <url>");
        lines.push(`    <loc>${url}</loc>`);
        lines.push(`    <lastmod>${today}</lastmod>`);
        lines.push(`    <changefreq>${changefreq}</changefreq>`);
        lines.push(`    <priority>${priority}</priority>`);
        lines.push("  </url>");
    });

    lines.push("</urlset>");
    return lines.join("\n");
}

function run() {
    const config = loadConfig();
    const publicRoutes = new Set(config.routes.public || []);
    const excludedRoutes = new Set(config.routes.labs || []);

    const files = walk(repoRoot);
    const discovered = files.map(toRoute);
    const filtered = discovered.filter((route) => {
        if (excludedRoutes.has(route)) return false;
        if (route.startsWith("/labs/")) return false;
        return publicRoutes.has(route);
    });

    const missing = [...publicRoutes].filter((route) => !filtered.includes(route));
    const unique = Array.from(new Set(filtered)).sort();

    const sitemap = buildSitemap(unique, config.siteUrl);
    fs.writeFileSync(path.join(repoRoot, "sitemap.xml"), sitemap, "utf8");

    const debug = {
        generatedAt: new Date().toISOString(),
        included: unique,
        missing,
        excluded: [...excludedRoutes],
        discoveredCount: discovered.length,
    };
    fs.writeFileSync(
        path.join(repoRoot, "sitemap-pages.json"),
        JSON.stringify(debug, null, 2),
        "utf8",
    );
}

run();
